### ISSUE TITLE
Stormrunner hangs under openjdk-jre in RCX bay

### ISSUE THREAD

**Issue by EvelynSubarrow** [EvelynSubarrow/Stormrunner#4]
Reported by David, and successfully replicated with OpenJDK JRE (ver 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 not that it probably matters). 

When starting a new game, in the RCX bay, when generating a new RCX, the arm from below unlocks, sinks down one step, then freezes in place. The sound for it sinking never plays. The UI appears responsive, and the game will be rerendered if the window is minimised, but attempting to click on anything in the UI will kill the rendering.

This is one of the earlier examples of looped audio in Stormrunner, and sound is an obviously potentially flaky area of difference between Open and Oracle JREs. A debugger may shed some light.

**Comment by EvelynSubarrow** [comment]
A thread dump is probably more the way to go, but this is roughly how to attach JDB, for the sake of future me
```
# (in a dir with stormrunner-1.3.0-all.jar)
jar -xf stormrunner-1.3.0-all.jar -C srt
/usr/lib/jvm/java-8-openjdk-amd64/bin/jdb -sourcepath srt -classpath "stormrunner-1.3.0-all.jar:srt" moe.evelyn.games.stormrunner.Main
```

**Comment by EvelynSubarrow** [comment]
thread dump (kill -3 and it dumps to stdout? stderr? not sure but it's in my terminal)
```
2021-04-17 23:35:29
Full thread dump OpenJDK 64-Bit Server VM (25.282-b08 mixed mode):

"Thread-4" #40 prio=6 os_prio=0 tid=0x00007f261400d800 nid=0x1af357 waiting for monitor entry [0x00007f25fb8f9000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.classpath.icedtea.pulseaudio.Operation.waitForCompletion(Operation.java:149)
	- waiting to lock <0x000000070853ea48> (a java.lang.Object)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.getBytesInBuffer(PulseAudioDataLine.java:493)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.getBytesInBuffer(PulseAudioSourceDataLine.java:51)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.drain(PulseAudioSourceDataLine.java:278)
	- locked <0x0000000708d17598> (a org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine)
	at com.sun.media.sound.DataPusher.run(DataPusher.java:220)
	at java.lang.Thread.run(Thread.java:748)

"Thread-3" #39 prio=6 os_prio=0 tid=0x00007f2614006000 nid=0x1af34b in Object.wait() [0x00007f25fbffe000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.classpath.icedtea.pulseaudio.Operation.waitForCompletion(Operation.java:153)
	- locked <0x000000070853ea48> (a java.lang.Object)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.drain(PulseAudioSourceDataLine.java:298)
	at com.sun.media.sound.DataPusher.run(DataPusher.java:220)
	at java.lang.Thread.run(Thread.java:748)

"Thread-2" #38 prio=6 os_prio=0 tid=0x00007f261400a000 nid=0x1af342 waiting for monitor entry [0x00007f25fb227000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.flush(PulseAudioSourceDataLine.java:312)
	- waiting to lock <0x000000070853ea48> (a java.lang.Object)
	at com.sun.media.sound.DataPusher.run(DataPusher.java:231)
	at java.lang.Thread.run(Thread.java:748)

"Animation Sequence" #37 prio=6 os_prio=0 tid=0x00007f2620098000 nid=0x1af33e waiting for monitor entry [0x00007f25fbefd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:131)
	- waiting to lock <0x000000070853ea48> (a java.lang.Object)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
	- locked <0x0000000708d415c8> (a org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
	at com.sun.media.sound.DataPusher.start(DataPusher.java:107)
	- locked <0x0000000708d41578> (a com.sun.media.sound.DataPusher)
	at com.sun.media.sound.DataPusher.start(DataPusher.java:91)
	- locked <0x0000000708d41578> (a com.sun.media.sound.DataPusher)
	at sun.audio.AudioDevice.startSampled(AudioDevice.java:118)
	- locked <0x0000000708663340> (a sun.audio.AudioDevice)
	at sun.audio.AudioDevice.openChannel(AudioDevice.java:212)
	- locked <0x0000000708663340> (a sun.audio.AudioDevice)
	at sun.audio.AudioPlayer.start(AudioPlayer.java:133)
	- locked <0x0000000708663148> (a sun.audio.AudioPlayer)
	at com.templar.games.stormrunner.templarutil.audio.SunSound.play(SunSound.java:92)
	at com.templar.games.stormrunner.templarutil.audio.SunAudioDevice.playMethod(SunAudioDevice.java:109)
	at com.templar.games.stormrunner.templarutil.audio.AudioManager.play(AudioManager.java:79)
	at com.templar.games.stormrunner.templarutil.audio.AudioManager.play(AudioManager.java:62)
	at com.templar.games.stormrunner.templarutil.animation.AnimationManager.playSound(AnimationManager.java:218)
	at com.templar.games.stormrunner.templarutil.animation.Sequence.run(Sequence.java:209)
	at java.lang.Thread.run(Thread.java:748)

"StateThread" #34 prio=6 os_prio=0 tid=0x00007f25eca7b800 nid=0x1af337 waiting on condition [0x00007f25fb328000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.templar.games.stormrunner.GameState.run(GameState.java:295)
	at java.lang.Thread.run(Thread.java:748)

"UtilityThread Executing: public synchronized boolean com.templar.games.stormrunner.GameApplet.cacheClean()" #29 prio=6 os_prio=0 tid=0x00007f25ecbdd000 nid=0x1af332 waiting on condition [0x00007f25fbafb000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.templar.games.stormrunner.templarutil.util.UtilityThread.run(UtilityThread.java:167)

"Image Animator 0" #28 daemon prio=3 os_prio=0 tid=0x00007f25ec4ab800 nid=0x1af331 waiting on condition [0x00007f25fb62b000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at sun.awt.image.GifFrame.dispose(GifImageDecoder.java:670)
	at sun.awt.image.GifImageDecoder.readImage(GifImageDecoder.java:458)
	at sun.awt.image.GifImageDecoder.produceImage(GifImageDecoder.java:212)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)

"Image Animator 0" #27 daemon prio=3 os_prio=0 tid=0x00007f25eca3e000 nid=0x1af330 waiting on condition [0x00007f25fb72c000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at sun.awt.image.GifFrame.dispose(GifImageDecoder.java:670)
	at sun.awt.image.GifImageDecoder.readImage(GifImageDecoder.java:458)
	at sun.awt.image.GifImageDecoder.produceImage(GifImageDecoder.java:212)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)

"Image Animator 0" #26 daemon prio=3 os_prio=0 tid=0x00007f25ec4d3800 nid=0x1af32e waiting on condition [0x00007f25fbbfc000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at sun.awt.image.GifFrame.dispose(GifImageDecoder.java:670)
	at sun.awt.image.GifImageDecoder.readImage(GifImageDecoder.java:458)
	at sun.awt.image.GifImageDecoder.produceImage(GifImageDecoder.java:212)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)

"PulseAudio Eventloop Thread" #23 daemon prio=6 os_prio=0 tid=0x00007f2620070800 nid=0x1af32b waiting for monitor entry [0x00007f2658157000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine$3.update(PulseAudioDataLine.java:215)
	- waiting to lock <0x0000000708d17598> (a org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine)
	at org.classpath.icedtea.pulseaudio.Stream.playbackStartedCallback(Stream.java:688)
	- locked <0x0000000708d17968> (a java.util.LinkedList)
	at org.classpath.icedtea.pulseaudio.EventLoop.native_iterate(Native Method)
	at org.classpath.icedtea.pulseaudio.EventLoop.run(EventLoop.java:133)
	- locked <0x000000070853ea48> (a java.lang.Object)
	at java.lang.Thread.run(Thread.java:748)

"Audio Player" #22 daemon prio=10 os_prio=0 tid=0x00007f2620026000 nid=0x1af322 waiting on condition [0x00007f2659ac0000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at sun.audio.AudioPlayer.run(AudioPlayer.java:176)

"Thread-0" #21 daemon prio=5 os_prio=0 tid=0x00007f2628004800 nid=0x1af314 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"DestroyJavaVM" #20 prio=5 os_prio=0 tid=0x00007f268c00b000 nid=0x1af302 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Image Animator 3" #18 daemon prio=3 os_prio=0 tid=0x00007f268c6f1800 nid=0x1af31a waiting on condition [0x00007f26597bd000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at sun.awt.image.GifFrame.dispose(GifImageDecoder.java:670)
	at sun.awt.image.GifImageDecoder.readImage(GifImageDecoder.java:458)
	at sun.awt.image.GifImageDecoder.produceImage(GifImageDecoder.java:212)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)

"Image Animator 2" #17 daemon prio=3 os_prio=0 tid=0x00007f268c6b9000 nid=0x1af319 waiting on condition [0x00007f26598be000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at sun.awt.image.GifFrame.dispose(GifImageDecoder.java:670)
	at sun.awt.image.GifImageDecoder.readImage(GifImageDecoder.java:458)
	at sun.awt.image.GifImageDecoder.produceImage(GifImageDecoder.java:212)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)

"AWT-EventQueue-1" #14 prio=6 os_prio=0 tid=0x00007f268c45c800 nid=0x1af316 waiting for monitor entry [0x00007f2659bbf000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at sun.audio.AudioPlayer.start(AudioPlayer.java:133)
	- waiting to lock <0x0000000708663148> (a sun.audio.AudioPlayer)
	at com.templar.games.stormrunner.templarutil.audio.SunSound.play(SunSound.java:92)
	at com.templar.games.stormrunner.templarutil.audio.SunAudioDevice.playMethod(SunAudioDevice.java:109)
	at com.templar.games.stormrunner.templarutil.audio.AudioManager.play(AudioManager.java:79)
	at com.templar.games.stormrunner.templarutil.audio.AudioManager.play(AudioManager.java:62)
	at com.templar.games.stormrunner.build.BuildPanel.error(BuildPanel.java:370)
	at com.templar.games.stormrunner.build.BuildPanel.error(BuildPanel.java:375)
	at com.templar.games.stormrunner.build.BuildPanel.actionPerformed(BuildPanel.java:964)
	- locked <0x0000000708c98a68> (a com.templar.games.stormrunner.build.BuildPanel)
	at com.templar.games.stormrunner.templarutil.gui.ImageButton.processActionEvent(ImageButton.java:320)
	- locked <0x0000000708c99638> (a com.templar.games.stormrunner.templarutil.gui.ImageButton)
	at com.templar.games.stormrunner.templarutil.gui.ImageButton.event(ImageButton.java:473)
	at com.templar.games.stormrunner.templarutil.gui.ImageButton$MouseHandler.mouseReleased(ImageButton.java:603)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at java.awt.Component.processEvent(Component.java:6304)
	at com.templar.games.stormrunner.templarutil.gui.ImageButton.processEvent(ImageButton.java:342)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

"AWT-Shutdown" #13 prio=5 os_prio=0 tid=0x00007f268c45b000 nid=0x1af315 in Object.wait() [0x00007f2659cc2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000706d9a998> (a java.lang.Object)
	at java.lang.Object.wait(Object.java:502)
	at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
	- locked <0x0000000706d9a998> (a java.lang.Object)
	at java.lang.Thread.run(Thread.java:748)

"AWT-XAWT" #11 daemon prio=6 os_prio=0 tid=0x00007f268c390800 nid=0x1af311 runnable [0x00007f265ad53000]
   java.lang.Thread.State: RUNNABLE
	at sun.awt.X11.XToolkit.waitForEvents(Native Method)
	at sun.awt.X11.XToolkit.run(XToolkit.java:570)
	at sun.awt.X11.XToolkit.run(XToolkit.java:534)
	at java.lang.Thread.run(Thread.java:748)

"Java2D Disposer" #9 daemon prio=10 os_prio=0 tid=0x00007f268c369800 nid=0x1af310 in Object.wait() [0x00007f265ae5c000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x0000000706ddf1d8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:748)

"Service Thread" #8 daemon prio=9 os_prio=0 tid=0x00007f268c18a800 nid=0x1af30e runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007f268c187800 nid=0x1af30d waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f268c185800 nid=0x1af30c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f268c182800 nid=0x1af30b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f268c17d000 nid=0x1af30a waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f268c14f000 nid=0x1af309 in Object.wait() [0x00007f2668472000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x0000000706feaf08> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f268c14a800 nid=0x1af308 in Object.wait() [0x00007f2668573000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x0000000706feb138> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=0 tid=0x00007f268c140800 nid=0x1af307 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f268c020800 nid=0x1af303 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f268c022800 nid=0x1af304 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007f268c024800 nid=0x1af305 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007f268c026000 nid=0x1af306 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f268c18d000 nid=0x1af30f waiting on condition 

JNI global references: 417


Found one Java-level deadlock:
=============================
"Thread-4":
  waiting to lock monitor 0x00007f2660004b48 (object 0x000000070853ea48, a java.lang.Object),
  which is held by "PulseAudio Eventloop Thread"
"PulseAudio Eventloop Thread":
  waiting to lock monitor 0x00007f2660004bf8 (object 0x0000000708d17598, a org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine),
  which is held by "Thread-4"

Java stack information for the threads listed above:
===================================================
"Thread-4":
	at org.classpath.icedtea.pulseaudio.Operation.waitForCompletion(Operation.java:149)
	- waiting to lock <0x000000070853ea48> (a java.lang.Object)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.getBytesInBuffer(PulseAudioDataLine.java:493)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.getBytesInBuffer(PulseAudioSourceDataLine.java:51)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.drain(PulseAudioSourceDataLine.java:278)
	- locked <0x0000000708d17598> (a org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine)
	at com.sun.media.sound.DataPusher.run(DataPusher.java:220)
	at java.lang.Thread.run(Thread.java:748)
"PulseAudio Eventloop Thread":
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine$3.update(PulseAudioDataLine.java:215)
	- waiting to lock <0x0000000708d17598> (a org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine)
	at org.classpath.icedtea.pulseaudio.Stream.playbackStartedCallback(Stream.java:688)
	- locked <0x0000000708d17968> (a java.util.LinkedList)
	at org.classpath.icedtea.pulseaudio.EventLoop.native_iterate(Native Method)
	at org.classpath.icedtea.pulseaudio.EventLoop.run(EventLoop.java:133)
	- locked <0x000000070853ea48> (a java.lang.Object)
	at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.

Heap
 PSYoungGen      total 103936K, used 2973K [0x0000000782380000, 0x0000000789080000, 0x00000007c0000000)
  eden space 96256K, 3% used [0x0000000782380000,0x0000000782667710,0x0000000788180000)
  from space 7680K, 0% used [0x0000000788900000,0x0000000788900000,0x0000000789080000)
  to   space 7680K, 0% used [0x0000000788180000,0x0000000788180000,0x0000000788900000)
 ParOldGen       total 126976K, used 37786K [0x0000000706a00000, 0x000000070e600000, 0x0000000782380000)
  object space 126976K, 29% used [0x0000000706a00000,0x0000000708ee6b10,0x000000070e600000)
 Metaspace       used 15252K, capacity 15560K, committed 15872K, reserved 1062912K
  class space    used 1871K, capacity 1982K, committed 2048K, reserved 1048576K
```

**Comment by EvelynSubarrow** [comment]
Pre-emptively added a decompiled surrogate for com/templar/games/stormrunner/templarutil/audio/AudioManager

Relevant thread dump extract
```
"Animation Sequence" #35 prio=6 os_prio=0 tid=0x00007f5e80097800 nid=0x1aff90 waiting for monitor entry [0x00007f5ed1ffc000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:131)
	- waiting to lock <0x00000007088c67e0> (a java.lang.Object)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
	- locked <0x000000070901c260> (a org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
	at com.sun.media.sound.DataPusher.start(DataPusher.java:107)
	- locked <0x000000070901c320> (a com.sun.media.sound.DataPusher)
	at com.sun.media.sound.DataPusher.start(DataPusher.java:91)
	- locked <0x000000070901c320> (a com.sun.media.sound.DataPusher)
	at sun.audio.AudioDevice.startSampled(AudioDevice.java:118)
	- locked <0x0000000708e75c70> (a sun.audio.AudioDevice)
	at sun.audio.AudioDevice.openChannel(AudioDevice.java:212)
	- locked <0x0000000708e75c70> (a sun.audio.AudioDevice)
	at sun.audio.AudioPlayer.start(AudioPlayer.java:133)
	- locked <0x0000000708e75a78> (a sun.audio.AudioPlayer)
	at com.templar.games.stormrunner.templarutil.audio.SunSound.play(SunSound.java:92)
	at com.templar.games.stormrunner.templarutil.audio.SunAudioDevice.playMethod(SunAudioDevice.java:109)
	at com.templar.games.stormrunner.templarutil.audio.AudioManager.play(AudioManager.java:62)
	at com.templar.games.stormrunner.templarutil.audio.AudioManager.play(AudioManager.java:48)
	at com.templar.games.stormrunner.templarutil.animation.AnimationManager.playSound(AnimationManager.java:218)
	at com.templar.games.stormrunner.templarutil.animation.Sequence.run(Sequence.java:209)
	at java.lang.Thread.run(Thread.java:748)
```

Relevant extract from AudioManager
```
    public void play(String string) {
        this.play(string, null); // <- 48
    }

    public void play(String string, SoundListener soundListener) {
        if (this.muted) {
            if (soundListener != null) {
                soundListener.soundStopped(string, 2);
            }
            return;
        }
        Sound sound = (Sound)this.audioCache.get(string);
        if (sound != null) {
            SoundRecord soundRecord = new SoundRecord(string, sound, this, soundListener, false);
            this.soundRecords.addElement(soundRecord);
            this.device.playMethod(soundRecord); // <- 62
            return;
        }
        System.err.println("AudioManager: play(): No such sound: " + string);
    }
```

**Comment by EvelynSubarrow** [comment]
Printing out the sound name and millisecond timing of each sound play, and this is so far 100% reproducible although as far as I can tell the actual deadlock isn't being specifically caused by the last sound request, it's just hitting it regardless. It's not special, as far as I can tell, I've put similar prints in the loop and stop methods but these turn up nothing.
```
1618704755198: ButtonClick
1618704857060: Build-Arm-Tools
1618704859684: Build-Arm-Tools
1618704864154: Robot-Happy
1618704866269: Build-Arm-Tools
```

**Comment by EvelynSubarrow** [comment]
Disabled nonlooped sound in the audiomanager and the issue no longer occurs, so it's definitely *something* sound...

**Comment by EvelynSubarrow** [comment]
If I prevent "Build-Arm-Tools" from playing, the result is that the game hangs the moment you attempt to add the chassis

**Comment by EvelynSubarrow** [comment]
The sound next after Robot-Happy will always block and hang - perhaps it's an issue with that sound itself somehow?

**Comment by EvelynSubarrow** [comment]
If Robot-Happy alone is blocked, you can add a chassis and the arm just fine, but the sensors will cause a hang. These sounds are notable because they're among the smaller sounds in that segment of the game, although oddly, button presses apparently don't cause the deadlock problem (and I've tried very hard to make it happen)

**Comment by EvelynSubarrow** [comment]
I've discussed this with people who know far more about the java ecosystem than I could possibly ever hope to, and apparently this is something of a debian/ubuntu specific problem with respect to the pulseaudio bindings. Apparently other versions of OpenJDK are available without this issue. I'm going to do some testing with one of those to work out a reliable test for the presence of these bindings, and disable sound in the event they're detected.
